name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Project declares requires-python = ">=3.11" in pyproject.toml
        # Keep CI Python versions aligned with project requirement to avoid false failures
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install pylint only; project has no build-system declared in pyproject.toml,
        # so avoid calling `pip install .` which may fail. If you add a build-system,
        # change this to install project packages as needed.
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
